### ISSUE TITLE
useContractWrite param error

### ISSUE THREAD

**Issue by cshung1994** [thirdweb-dev/js#1008]
There is no way to pass parameters through the array to the useContractWrite function, after I installed react-select.

![2023-05-15 16 34 08](https://github.com/thirdweb-dev/js/assets/33892812/c5efa357-0398-44da-b9b4-07c5f6c05f21)
<img width="387" alt="截圖 2023-05-15 下午4 35 28" src="https://github.com/thirdweb-dev/js/assets/33892812/ff95fade-080a-4a43-9d3e-922eeebce038">

**Comment by adam-maj** [comment]
@cshung1994 Could you show what the `contractMint` function looks like/where it's coming from?

**Comment by hunkydoryrepair** [comment]
How was this completed? It is still badly broken.
The code was broken with this commit:

https://github.com/thirdweb-dev/js/commit/1137a20de44603d35e71eae2f2b6fec79febec00

it was changed so that you must now call it like this:

`contractMint({ args: [url, tier], overrides: { value: ethers.util.parseEther(gas) }});`

I don't think this was intentional, or if it was, the documentation was not (fully)  updated.

**Comment by MananTank** [comment]
Hi @hunkydoryrepair - the API change is intentional. 
Thanks for pointing out the inaccuracy of the docs - We will update it ASAP.
