### ISSUE TITLE
React Native - ThirdWeb doesn't work JSC engine

### ISSUE THREAD

**Issue by Patel-Preet** [thirdweb-dev/js#1582]
I am using Tensorflow as one of the dependencies and it requires Hermes to be disabled. 
When switched to JSC, I get error (likely to be parsing error)

```
Unexpected token '='
Unexpected token '='
no stack
no stack
```

Versions:
```
"@thirdweb-dev/react-native": "^0.2.58",
"@thirdweb-dev/react-native-compat": "^0.2.58",
```

Issue can be replicated by following:
If using expo, after pre-build -> Go to gradle.properties -> `hermesEnabled=false`

**Comment by iketw** [comment]
@Patel-Preet, I can repro your issue. I'm looking into this but in the mean time can you try running the app in Debug mode? You can press `Command + M` on Mac or `Ctrl + M` on Windows to show the RN DevMenu, then press Debug. For some reason that fixes the error and it will allow you to code while we find a solution.

<img width="317" alt="Screenshot 2023-09-05 at 2 55 07 PM" src="https://github.com/thirdweb-dev/js/assets/121973632/9150c70c-be06-496b-9cbf-b0938cf0e1aa">

**Comment by iketw** [comment]
@Patel-Preet I believe I found the issue here. We use Logical OR Assignments in our sdks and that's not supported with JSC out of the box (https://github.com/facebook/react-native/issues/31704).

Can you try adding the following plugin to your app:

`yarn add --dev @babel/plugin-proposal-logical-assignment-operators`

and then add the plugin to your babel.config.js file:

`plugins: ['@babel/plugin-proposal-logical-assignment-operators']`

Please, let me know if this works for you.
