### ISSUE TITLE
When will Thirdweb give support for Next.js App Router?

### ISSUE THREAD

**Issue by hsynaldgrn** [thirdweb-dev/js#2022]
Next.js App Router became stable since [May 4, 2023](https://nextjs.org/blog/next-13-4).
However Thirdweb Auth SDK has no support for App Router according to [that document](https://portal.thirdweb.com/auth/server-frameworks/next#getting-started).

Is there any development roadmap?

**Comment by MananTank** [comment]
Hi @hsynaldgrn - the `@thirdweb-dev/react` can already be used in App router. Please refer to "Next.js > App router" section in https://portal.thirdweb.com/react/getting-started. 

Since you can use both App router and Pages router at the same time, You can create the auth endpoint in Pages router and rest of your app in App router for now. We will add the official support App router for Auth SDK soon

**Comment by hsynaldgrn** [comment]
Thank you. We would like to wait for the App Router support if it will come soon :)
