### ISSUE TITLE
NPX not running 

### ISSUE THREAD

**Issue by crossxmint** [thirdweb-dev/js#2038]
![Screenshot 2023-12-04 041231](https://github.com/thirdweb-dev/js/assets/152814402/17b9502d-4d0c-48e5-a601-84e754c67a16)
Can anyone help me solve this issue please. I have already seperately installed both CLI from windows store and also GIT. but still cannot run thirdweb command. I am a complete beginner i would really appreciate your guys help

**Comment by MananTank** [comment]
Hi @crossxmint, This issue is not related to thirdweb CLI - you need to download `npx` globally in your system to use it use `npx`. Refer to https://docs.npmjs.com/cli/v7/commands/npx for more info

It is usually installed when you install npm/node

You can also install it manually by running `npm i -g npx` on windows or `sudo npm i -g npx`
