### ISSUE TITLE
[SDK] - Add support for getting all token holder balances

### ISSUE THREAD

**Issue by jarrodwatts** [thirdweb-dev/js#241]
## Description

With ERC20 tokens, you should be able to get all the current holders and their balances:

```jsx
const token = sdk?.getToken("0xEB0e3E54103AD8dBe298b86474d7AA08cc680776");
const hist = token.history;
const balances = hist.getAllHolderBalances();
```

Right now, `history` is undefined when you try to access this.

## Goal

Find and resolve the bug in this logic above within the `\packages\sdk\src\core\classes\erc-20-history.ts` file.

**Comment by simonlim94** [comment]
Hi @jarrodwatts , I would like to contribute but I am not JS expert. I hope you don't mind if I ask something (probably stupid) here. With the code above, if I tested it using `async`, it seems like there is no such issue

```
const token = await sdk?.getToken('0xEB0e3E54103AD8dBe298b86474d7AA08cc680776');
const hist = token.history;
const balances = await hist.getAllHolderBalances();
```
since `token` returns promise here, if we don't use `async`, it will not be waited to be resolved and `history` will be undefined in that case? So what kind of goal if that is the case? Of course you don't expect it to be converted to synchronous method right? :)

**Comment by jarrodwatts** [comment]
This looks correct @simonlim94! 

Looks like I made a mistake with the `async` here.

Thank you for pointing that out! Closing this one.
