### ISSUE TITLE
Not able to connect when user has Linea Mainnet in Metamask

### ISSUE THREAD

**Issue by mominnawaf** [thirdweb-dev/js#2411]
When the user is already connected to `Linea Mainnet`, the user initiates and approves the connection. Thirdweb SDK is not sending the callback. It works fine for `Polygon Mainnet` or `Ethereum Mainnet`.
Below is the React Component: 
```ts
import React, { useEffect } from "react";
import {
  useSetIsWalletModalOpen,
  useChain,
  useConnectionStatus,
  useAddress,
  useDisconnect,
} from "@thirdweb-dev/react";

const ThirdWebComponenet = ({ closeModal }: Props): React.JSX.Element => {
  const address = useAddress();
  const chain = useChain();
  const connectionStatus = useConnectionStatus();

  useEffect(() => {
    if (
      connectionStatus === "connected" &&
      address !== undefined &&
      chain?.chainId !== undefined
    ) {
      console.log(chain.chainId.toString(), address); //not logging
    }
  }, [address, connectionStatus, chain]);

  const setIsWalletModalOpen = useSetIsWalletModalOpen();
  const openModal = (): void => {
    setIsWalletModalOpen(true);
  };

  return <button onClick={openModal}>Connect</button>;
};

export default ThirdWebComponenet;

```

**Comment by MananTank** [comment]
Hey @mominnawaf, the console log is not printed because of  `chain?.chainId !== undefined` condition. If you remove it, it will be logged successfully. 

If you are interested in the entire chain `chain` object of linea mainnet - you need to add that in `supportedChains` prop of `ThirdwebProvider` - If it's not added, thirdweb SDK can't create an object for it and you will only be able to see the chainId of the connected wallet which you can get by using `useChainId` hook instead

**Comment by mominnawaf** [comment]
Thanks, @MananTank appreciate the quick resolution..
