### ISSUE TITLE
Merkle tree not able to create single tree proofs

### ISSUE THREAD

**Issue by JoaoCampos89** [thirdweb-dev/js#2437]
Hi guys, I created tool for airdrops and used the example from here: https://github.com/thirdweb-example/claimable-erc20-youtube/blob/main/pages/index.tsx But if I use only one allowlist entry the getProofsForAllowListEntry from '@thirdweb-dev/react' is not able to create a proof.

 How to replicate, just create the same example but with an array like this [{address: 'an address', maxClaimable: 'amount' }]. If this is the intended behaviour, should at least throw an error if user is trying to build a tree with only one entry.

tagging @warengonzaga

**Comment by jnsdls** [comment]
Well look into this! Thanks for the report!

**Comment by BrianJRobinson** [comment]
I also had a problem with the MerkleTree code. I Found that when I had 2 items in the allowlist, the proofs were validating correctly in the ERC20Claimable solidity contract, but as soon as I created an allowlist with more than 2 items the proofs were coming up as invalid in the smart contract.

**Comment by joaquim-verges** [comment]
hey @JoaoCampos89 - for single entries in the allowlist, `getProofsForAllowListEntry` is expected to return an empty array. You can pass that to the contract and that should be valid. That is the expected behavior for a single entry merkle tree.

Also I just improved the return type of that function so you get the hashes back instead of a buffer here https://github.com/thirdweb-dev/js/pull/2469

feel free to push a PR to the template you linked!

cc @watase-eth
