### ISSUE TITLE
SDK-Can not getContractList when deploy contract use GASLESS.

### ISSUE THREAD

**Issue by legiarung** [thirdweb-dev/js#248]
When i deploy contract with network GEORI and success.
Then I use method `const list = await sdk.getContractList(currentAddress)` to get all List contract .

I get the result that no contracts can be found deployed using gasless and using a regular wallet is successful.

I tested with RINKEBY network, it was successful and no error
Can you help me to test GEORI network and mainnet networks.

**Comment by joaquim-verges** [comment]
Deploying gasless-ly is dangerous because the deployer can be the gasless relayer. This is probably why you're not seeing the contracts in the contract list of the original caller. The deployer address is probably your relayer

**Comment by legiarung** [comment]
@joaquim-verges 

Oh i see, ie it will be deployed with the wallet registered in openzeplin. So how when a customer uses gasless to sign a contract but uses gasless, the customer is still the owner of that contract. Do you have any workarounds?
Thank you

**Comment by joaquim-verges** [comment]
The way it works for gasless tx is that on the relayer (like OZ defender) we use a Forwarder contract to propagate the address of the caller to the target contract. That works for regular contract calls, which can then read that original caller address, but it doesn't work for direct deploys, since those cannot extract the original caller address. It is possible to make it work using a Factory contract to deploy the contracts though
