### ISSUE TITLE
The signature doesn't match the address in a smart wallet

### ISSUE THREAD

**Issue by mmahdigh** [thirdweb-dev/js#2877]
How to reproduce:

1- Sign a random string message with the smart wallet (Which is itself created from an embedded wallet)

```ts
const signMessage = useActiveAccount()?.signMessage

const message = "A random message"
const signature = await signMessage({
  message,
})
```

2- Check the signature hash to see if it matches the address (You can use [Etherscan](https://etherscan.io/verifiedSignatures) for this)

For instance, I as the owner of the `mghfcp2023@gmail.com` create an EOA.
Then with this EOA, I create a smart wallet with this address: `0xcb73a971e3643f756E0Ce8c81cccA3D7B6AB2b9d`
Then, I would run the above code and check the signature in the Etherscan like below and the verification fails:

![image](https://github.com/thirdweb-dev/js/assets/46849131/c45bdd0a-310a-443b-8e6b-c544aff87697)

P.S: I also checked with [siwe ](https://github.com/spruceid/siwe.git)library in a Node.js server and the signature was invalid there too.

Environment:

```json
"next": "14.1.4",
"react": "^18",
"react-dom": "^18",
"thirdweb": "^5.3.1"
```

**Comment by gregfromstl** [comment]
Hey @mmahdigh, thanks for reporting this. I've reproduced the issue and will get a fix out ASAP. Will report back here with updates

**Comment by gregfromstl** [comment]
Hey @mmahdigh, thanks for opening this. Smart accounts aren't able to generate signatures like EOAs since they don't have a private key, so we use [EIP-1271](https://eips.ethereum.org/EIPS/eip-1271) to generate and verify signatures through the account's smart contract.

You can use the [verifySignature](https://portal.thirdweb.com/references/typescript/v5/verifySignature) function and it will call your account's smart contract to verify the signature **(make sure to include the optional chain and client options for it to do this)**. Does that help?

**Comment by mmahdigh** [comment]
> Hey @mmahdigh, thanks for opening this. Smart accounts aren't able to generate signatures like EOAs since they don't have a private key, so we use [EIP-1271](https://eips.ethereum.org/EIPS/eip-1271) to generate and verify signatures through the account's smart contract.
> 
> You can use the [verifySignature](https://portal.thirdweb.com/references/typescript/v5/verifySignature) function and it will call your account's smart contract to verify the signature **(make sure to include the optional chain and client options for it to do this)**. Does that help?

Thank you! It makes sense.
