### ISSUE TITLE
Reported PLYR TAU on thirdweb.com/chainlist doesn't correct

### ISSUE THREAD

**Issue by iamcryptofennec** [thirdweb-dev/js#3047]
https://thirdweb.com/plyr-tau-testnet

![image](https://github.com/thirdweb-dev/js/assets/128964/6b33c66c-b6c6-43aa-8d6b-45c9936ddc43)

icon : ipfs://QmVhG7xeTc78ibQunQ5sBJ4533r9FDM2xUCQKV72DPd1ux
from ethereum-list -> https://github.com/ethereum-lists/chains/blob/master/_data/icons/plyr.json

and info is : https://plyr.network not avacloud.io

**Comment by jnsdls** [comment]
hi @iamcryptofennec this is due to the chain being added directly via our avacloud integration, I am currently unaware if avacloud has a way for the creator of the chain to update these values? If so then that should also update them correctly inside thirdweb, if not then we'll have to figure out a new path here.

**Comment by iamcryptofennec** [comment]
Hi, I don't see any way to update those infomation on Avaclouds platform. Is it possible to change direct on Thirdweb chainlist page?

**Comment by eabdelmoneim** [comment]
@iamcryptofennec this information has been updated now https://thirdweb.com/plyr-tau-testnet

**Comment by iamcryptofennec** [comment]
> @iamcryptofennec this information has been updated now https://thirdweb.com/plyr-tau-testnet

![image](https://github.com/thirdweb-dev/js/assets/128964/2fef300a-4ad4-42a6-b79d-1e55c9128831)

Info url is correct. but Logo not correct and gone.
