### ISSUE TITLE
Selecting Metamask wallet from Connect Wallet Modal always connects to Rabby Wallet (Even after banning Rabby wallet from the settings in Rabby wallet extension)

### ISSUE THREAD

**Issue by codingfarhan** [thirdweb-dev/js#3133]
Hey guys, whenever I select Metamask wallet from Connect Wallet modal it instead connects to the Rabby wallet all the time. I have tried different ways to disable this behavior but it keeps happening. Any suggestions/tips on how to solve this problem?
Btw I have Rabby wallet and Metamask wallet installed as the chrome extensions.

**Note**: But if I refresh the page and try and connect in a different page it works. This is not a desired behavior for our app.

Please find the attached videos to see the different methods I've tried to resolve this problem.

Thanks in advance! :)

https://github.com/thirdweb-dev/js/assets/40217589/d35239c5-e908-4e1e-8fb0-e60cd4826cfc

https://github.com/thirdweb-dev/js/assets/40217589/796451f7-1a49-48f6-8520-b5ebe7fda80a

**Comment by jnsdls** [comment]
@codingfarhan hey, thanks for the report - could you share your wallet configuration so we can try to reproduce it?

Even better would be if you could create a minimal reproduction case (github repo, stackblitz, or similar), it would massively speed up us hunting this down and fixing the issue. :)

**Comment by gregfromstl** [comment]
Hey @codingfarhan, this is actually expected behavior for Rabby. If you switch between Rabby and Metamask in the Rabby wallet you get this popup to let you know you have to refresh the page for the wallet to take effect.
![Screenshot 2024-05-23 at 6 05 10 PM](https://github.com/thirdweb-dev/js/assets/17715009/4463a9d3-7f66-49a2-b307-05ecd93389c6)
