### ISSUE TITLE
Why does Wanchain testnet chainid 999 conflicted with Zora-Testnet?

### ISSUE THREAD

**Issue by iamcryptofennec** [thirdweb-dev/js#3439]
https://thirdweb.com/zora-testnet

https://chainlist.org/chain/999 << it's Wanchain Testnet

**Comment by iamcryptofennec** [comment]
![image](https://github.com/thirdweb-dev/js/assets/128964/c0d9b9af-84bc-4e1a-bbc1-0b0e44f650ea)

On chainlist. Zora isn't the "999"

**Comment by jnsdls** [comment]
the correct zora testnet is here: https://thirdweb.com/zora-sepolia-testnet

looking into why 999 points at an (incorrect, and non-functional) zora testnet, thanks for the report

**Comment by jnsdls** [comment]
Resolved the conflict, it will however take some time to make it out via various layers of caching, here's what happened:

- zora launched their (goerli) testnet at chainId 999
- wanchain had been essentially "dead" for a long time (no usage, almost no available interaction)
- as such we (back then) decided to give zora testnet (again, goerli) the 999 chainId that they had selected

- since then zora has launched their (active) sepolia testnet, which is (correctly) at chainId: `999999999`
- we never removed the override for `999` (until today)

thanks again for pointing this out! it'll be fixed once caches clear out over the next hour or so


_this once again reinforces my belief that as an industry we need a better solution to organizing "what chains exist"_
