### ISSUE TITLE
CLI generate does not generate all methods

### ISSUE THREAD

**Issue by artiffine-vojtech** [thirdweb-dev/js#5164]
For some contracts, CLI generate does not generate all methods from the contract.

Example:
`yarn thirdweb generate 137/0x6b076D1bA0c748e349A3283CaF9D24b28Fd779FB`

Missing methods:
isAdmin
collectionFee
and many others...

All these methods are visible on the contract explorer:
https://polygonscan.com/address/0x6b076D1bA0c748e349A3283CaF9D24b28Fd779FB#readContract

How to generate the full contract interface? 

Thanks!

**Comment by joaquim-verges** [comment]
thanks for reporting this @artiffine-vojtech - we're looking into this

**Comment by catalyst17** [comment]
hello @artiffine-vojtech!
thank you for reporting the issue

we're constantly working on improving the automations with regards to serving proper contract metadata but sometimes it can still resolve wrongly

actually, for such a reason we are allowing our users to go and try refreshing the data themselves here:
https://thirdweb.com/polygon/0x6b076D1bA0c748e349A3283CaF9D24b28Fd779FB/sources
by using the `Refresh Contract Data` button

that is how I got your issue solved just now :)

let me know if you have any further questions or feel free to close the issue otherwise

enjoy building! 🚀
